app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



// Front Routes
Route::get('/', 'HomeController@index');

Route::post('/front-pegawai/search', [
    'as'  => 'front.pegawai.search',
    'uses'  => function() {
        $nip = Input::get('nip');

        return redirect(route('front.pegawai.show', $nip));
    }
]);

Route::get('/front-pegawai/{nip}', [
    'as'  => 'front.pegawai.show',
    'uses'  => 'HomeController@getPegawai'
]);


Route::group(['prefix' => 'cp', 'middleware' => 'auth'], function () {
	
	Route::get('dashboard', [
		'as' 	=> 	'cp.dashboard',
		'uses' 	=>	'PanelController@dashboard'
	]);

	Route::resource('pegawai', 'EmployeeController');

    Route::get('pegawai/{id}/file', [
        'as' => 'cp.pegawai.file',
        'uses' => 'EmployeeController@getFile'
        ]);

    Route::resource('instansi', 'InstituteController');

    Route::resource('jabatan', 'PositionController');

    Route::resource('callcenter', 'CallCenterController');

    Route::resource('users', 'UserController');

});

// Authentication Routes

Route::get('auth/login', 'Auth\AuthController@getLogin');

Route::post('auth/login', 'Auth\AuthController@postLogin');

Route::get('auth/logout', 'Auth\AuthController@getLogout');

resources/views/cp/pegawai/create.blade.php
@extends('cp.master')

@section('content')

<div class="row">	
	<div class="col-md-6 col-md-offset-2">
		<h1 class="page-header">Menambah Data Pegawai</h1>
		
		      <!-- Status Check -->
        @if (session('status'))
            <div class="alert alert-success">
              {{ session('status') }}
            </div>
        @endif
        <!-- Status Check -->
	
		{!! Form::open(['route' => 'cp.pegawai.store', 'method' => 'post', 'files' => true]) !!}			

			<div class="form-group {{ ($errors->first('nip')) ? 'has-error' : '' }}">
				<label for="nip">NIP</label>
				{!! Form::text('nip', null, ['class' => 'form-control']) !!}
				{!! ($errors->first('nip')) ? $errors->first('nip', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('nama')) ? 'has-error' : '' }}">
				<label for="nama">Nama</label>
				{!! Form::text('nama', null, ['class' => 'form-control']) !!}
				{!! ($errors->first('nama')) ? $errors->first('nama', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('no_telp')) ? 'has-error' : '' }}">
				<label for="no_telp">No. HP</label>
				{!! Form::text('no_telp', null, ['class' => 'form-control']) !!}
				{!! ($errors->first('no_telp')) ? $errors->first('no_telp', '<span class="help-block">:message</span>') : ''!!}			
			</div>

			<div class="form-group {{ ($errors->first('pendidikan')) ? 'has-error' : '' }}">
				<label for="pendidikan">Pendidikan</label>
				{!! Form::select('pendidikan', $pendidikan, null, ['id' => 'pendidikanPegawai', 'class' => 'form-control']) !!}
				{!! ($errors->first('pendidikan')) ? $errors->first('pendidikan', '<span class="help-block">:message</span>') : '' !!}
			</div>
			
			<div class="form-group {{ ($errors->first('instansi')) ? 'has-error' : '' }}">
				<label for="instansi">Instansi</label>
				{!! Form::select('instansi', $instansi, null, ['id' => 'instansiPegawai', 'class' => 'form-control']) !!}
				{!! ($errors->first('instansi')) ? $errors->first('instansi', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('jabatan')) ? 'has-error' : '' }}">
				<label for="jabatan">Jabatan</label>
				{!! Form::select('jabatan', $jabatan, null, ['id' => 'jabatanPegawai', 'class' => 'form-control']) !!}
				{!! ($errors->first('jabatan')) ? $errors->first('jabatan', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('golongan')) ? 'has-error' : '' }}">
				<label for="golongan">Golongan</label>
				{!! Form::select('golongan', $golongan, null, ['id' => 'golonganPegawai', 'class' => 'form-control']) !!}
				{!! ($errors->first('golongan')) ? $errors->first('golongan', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('alamat')) ? 'has-error' : '' }}">
				<label for="alamat">Alamat</label>
				{!! Form::textarea('alamat', null, ['rows' => 3, 'class' => 'form-control']) !!}
				{!! ($errors->first('alamat')) ? $errors->first('alamat', '<span class="help-block">:message</span>') : '' !!}
			</div>
			
			<div class="form-group {{ ($errors->first('foto1')) ? 'has-error' : '' }}">
				<label for="foto1">Foto 1</label>
				<input type="file" name="foto1">
				{!! ($errors->first('foto1')) ? $errors->first('foto1', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('foto2')) ? 'has-error' : '' }}">
				<label for="foto2">Foto 2</label>
				<input type="file" name="foto2">
				{!! ($errors->first('foto2')) ? $errors->first('foto2', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('file')) ? 'has-error' : '' }}">
				<label for="file">File</label>
				<input type="file" name="file">
				{!! ($errors->first('file')) ? $errors->first('file', '<span class="help-block">:message</span>') : '' !!}
			</div>	
			
			<hr>
			
			<div class="form-group">				
				<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Simpan</button>
			</div>
			
		{!! Form::close() !!}
	</div>
</div>

@endsection

resources/views/cp/pegawai/edit.blade.php
@extends('cp.master')

@section('content')

<div class="row">	
	<div class="col-md-6 col-md-offset-2">
		<h1 class="page-header">Mengubah Data Pegawai</h1>
		
		@if(Session::has('error'))
			<div class="alert alert-danger">
				{{ Session::get('error') }}
			</div>
		@endif
	
		{!! Form::model($pegawai, ['route' => ['cp.pegawai.update', $pegawai->id], 'method' => 'put', 'files' => true]) !!}

			<div class="form-group {{ ($errors->first('nip')) ? 'has-error' : '' }}">
				<label for="nip">NIP</label>
				{!! Form::text('nip', $pegawai->id_number, ['class' => 'form-control']) !!}
				{!! ($errors->first('nip')) ? $errors->first('nip', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('nama')) ? 'has-error' : '' }}">
				<label for="nama">Nama</label>
				{!! Form::text('nama', $pegawai->name, ['class' => 'form-control']) !!}
				{!! ($errors->first('nama')) ? $errors->first('nama', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('no_telp')) ? 'has-error' : '' }}">
				<label for="no_telp">No. HP</label>
				{!! Form::text('no_telp', $pegawai->phone_number, ['class' => 'form-control']) !!}
				{!! ($errors->first('no_telp')) ? $errors->first('no_telp', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('pendidikan')) ? 'has-error' : '' }}">
				<label for="pendidikan">Pendidikan</label>
				{!! Form::select('pendidikan', $pendidikan, $pegawai->academic_degree_id, ['id' => 'pendidikanPegawai', 'class' => 'form-control']) !!}
				{!! ($errors->first('pendidikan')) ? $errors->first('pendidikan', '<span class="help-block">:message</span>') : '' !!}
			</div>
			
			<div class="form-group {{ ($errors->first('instansi')) ? 'has-error' : '' }}">
				<label for="instansi">Instansi</label>
				{!! Form::select('instansi', $instansi, $pegawai->institute_id, ['id' => 'instansiPegawai', 'class' => 'form-control']) !!}
				{!! ($errors->first('instansi')) ? $errors->first('instansi', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('jabatan')) ? 'has-error' : '' }}">
				<label for="jabatan">Jabatan</label>
				{!! Form::select('jabatan', $jabatan, $pegawai->position_id, ['id' => 'jabatanPegawai', 'class' => 'form-control']) !!}
				{!! ($errors->first('jabatan')) ? $errors->first('jabatan', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('golongan')) ? 'has-error' : '' }}">
				<label for="golongan">Golongan</label>
				{!! Form::select('golongan', $golongan, $pegawai->rank_id, ['id' => 'golonganPegawai', 'class' => 'form-control']) !!}
				{!! ($errors->first('golongan')) ? $errors->first('golongan', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('alamat')) ? 'has-error' : '' }}">
				<label for="alamat">Alamat</label>
				{!! Form::textarea('alamat', $pegawai->address, ['rows' => 3, 'class' => 'form-control']) !!}
				{!! ($errors->first('alamat')) ? $errors->first('alamat', '<span class="help-block">:message</span>') : '' !!}
			</div>
			
			<div class="row">
				<div class="col-md-6">
					<img src="{{ asset($pegawai->photo1) }}" height="160"  width="120" class="img img-responsive img-rounded" alt="">
				</div>
				<div class="col-md-6">
					<div class="form-group {{ ($errors->first('foto1')) ? 'has-error' : '' }}">
						<label for="foto1">Foto 1</label>
						<input type="file" name="foto1">
						{!! ($errors->first('foto1')) ? $errors->first('foto1', '<span class="help-block">:message</span>') : '' !!}
						<span class="help-block">* Pilih Untuk mengganti foto 1.</span>
					</div>
				</div>
			</div>

			<hr>
			
			<div class="row">
				<div class="col-md-6">
					<img src="{{ asset($pegawai->photo2) }}" height="160"  width="120" class="img img-responsive img-rounded" alt="">
				</div>
				<div class="col-md-6">					
					<div class="form-group {{ ($errors->first('foto2')) ? 'has-error' : '' }}">
						<label for="foto2">Foto 2</label>
						<input type="file" name="foto2">
						{!! ($errors->first('foto2')) ? $errors->first('foto2', '<span class="help-block">:message</span>') : '' !!}
						<span class="help-block">* Pilih Untuk mengganti foto 2.</span>
					</div>
				</div>
			</div>
			
			<hr>

			<div class="form-group {{ ($errors->first('file')) ? 'has-error' : '' }}">
				<label for="file">File</label>
				<input type="file" name="file">
				{!! ($errors->first('file')) ? $errors->first('file', '<span class="help-block">:message</span>') : '' !!}
				<span class="help-block">* Pilih Untuk mengganti file.</span>
				<br>
				<a href="{{ asset($pegawai->file) }}"  target="_blank">Lihat File</a>
			</div>	
			
			<hr>
			
			<div class="form-group">				
				<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Simpan Perubahan</button>
			</div>
			
		{!! Form::close() !!}
	</div>
</div>

@endsection

resources/views/cp/pegawai/index.blade.php
@extends('cp.master')

@section('content')
	
	<div class="row">
		<div class="col-md-12">
			<h1 class="page-header">Pegawai <small>data master</small> <a href="{{ route('cp.pegawai.create') }}" class="btn btn-primary pull-right">Tambah Data</a></h1>

			<form class="form-inline" style="text-align:right;">            		            
                <div class="form-group">
                	<label for="">Cari berdasar</label>
                	{!! Form::select('f_instansi', $instansi, Input::get('f_instansi'),	 ['class' => 'form-control input-sm']) !!}
                </div>
                <div class="form-group">
                	{!! Form::select('f_jabatan', $jabatan, Input::get('f_jabatan'), ['class' => 'form-control input-sm']) !!}
                </div>
                <div class="form-group">
                	{!! Form::select('f_field', ['nama' => 'Nama', 'nip' => 'NIP'], Input::get('f_field'), ['class' => 'form-control input-sm']) !!}
                </div>
	            <div class="form-group">
	                <input type="text" name="query" class="form-control input-sm" placeholder="Masukkan kata kunci" value="{{ Input::get('query') }}">
	            </div>
	            <input type="submit" class="btn btn-primary btn-sm" value="Cari">
	        </form>

	        @if (session('error-delete'))
	          <div class="alert alert-danger">
	            {{ session('error-delete') }}
	          </div>
	        @endif
	        
	        @if (session('success-delete'))
	          <div class="alert alert-success">
	            {{ session('success-delete') }}
	          </div>
	        @endif

			<hr>

			@if(!is_null(Input::get('query')))
				<blockquote>
				  <code>Menemukan {{ $pegawai->count() }} data.</code>
				</blockquote>				
			@endif
			
			<table class="table table-condensed table-striped table-hover">
				<thead>
					<tr>
						<th>NIP</th>
						<th>Nama</th>
						<th>No. HP</th>						
						<th>Jabatan</th>						
						<th>Instansi</th>						
						<th>Alamat</th>						
						<th style="width: 100px">Aksi</th>
						<th style="width: 100px">Lainnya</th>
					</tr>
				</thead>
				<tbody>

					@foreach($pegawai as $peg)
						
						<tr>
							<td>{{ $peg->id_number }}</td>
							<td>{{ $peg->name }}</td>
							<td>{{ $peg->phone_number }}</td>
							<td>{{ $peg->position->name }}</td>
							<td>{{ $peg->institute->name }}</td>
							<td>{{ $peg->address }}</td>
							<td>
								<a href="{{ action('EmployeeController@edit', ['id' => $peg->id]) }}" class="btn btn-warning btn-xs btn-block">Ubah</a>
								<a class="btn btn-danger btn-xs btn-block btn-delete" data-url="{{ action('EmployeeController@destroy', $peg->id) }}" data-title="{{ $peg->name }}">Hapus</a>																
							</td>
							<td>
								<a href="{{ action('EmployeeController@show', ['id' => $peg->id]) }}" class="btn btn-primary btn-xs btn-block">Lihat</a>
								<a href="" class="btn btn-default btn-xs btn-block">Download</a>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
			{!! $pegawai->render() !!}
		</div>
	</div>
@endsection

resources/views/cp/pegawai/show.blade.php
@extends('cp.master')

@section('content')

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1 class="page-header">Detail Pegawai <a href="{{ route('front.pegawai.show', $pegawai->id_number) }}" class="btn btn-default pull-right"><i class="glyphicon glyphicon-eye-open"></i> Lihat Live</a></h1>
			<div class="row">
				<div class="col-md-3 col-md-offset-3">
					<div class="thumbnail">
						<img src="{{ asset($pegawai->photo1) }}" alt="" class="img img-responsive img-rounded">
					</div>		
				</div>
				<div class="col-md-3">					
					<div class="thumbnail">
						<img src="{{ asset($pegawai->photo2) }}" alt="" class="img img-responsive img-rounded">
					</div>			
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<h3>{{ $pegawai->name }}</h3>
					<table class="table">
						<tbody style="font-weight: bold;">
							<tr>
								<td>NIP</td>
								<td>{{ $pegawai->id_number }}</td>
							</tr>
							<tr>
								<td>No. HP</td>
								<td>{{ $pegawai->phone_number }}</td>
							</tr>
							<tr>
								<td>alamat</td>
								<td>{{ $pegawai->address }}</td>
							</tr>
							<tr>
								<td>golongan</td>
								<td>{{ $pegawai->rank->rank }}</td>
							</tr>
							<tr>
								<td>Jabatan</td>
								<td>{{ $pegawai->position->name }}</td>
							</tr>
							<tr>
								<td>Instansi</td>
								<td>{{ $pegawai->institute->name }} <br> <i>Alamat: {{ $pegawai->institute->address }}</i></td>
							</tr>
							<tr>
								<td>pendidikan</td>
								<td>{{ $pegawai->academicDegree->name }}</td>
							</tr>
							<tr>
								<td>File</td>
								<td><a href="{{ asset($pegawai->file) }}">{{ asset($pegawai->file) }}</a></i></td>
							</tr>
						</tbody>
					</table>	
				</div>				
			</div>
		</div>
	</div>
@stop

resources/views/cp/pegawai/staff-card.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Staff Card</title>
	<style>
		.container {
			width: 960px;
			margin: 0 auto;
		}
	</style>
</head>
<body>
	<div class="container">
		<h1>Hello {{ $word }}</h1>
	</div>
</body>
</html>