app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



// Front Routes
Route::get('/', 'HomeController@index');

Route::post('/front-pegawai/search', [
    'as'  => 'front.pegawai.search',
    'uses'  => function() {
        $nip = Input::get('nip');

        return redirect(route('front.pegawai.show', $nip));
    }
]);

Route::get('/front-pegawai/{nip}', [
    'as'  => 'front.pegawai.show',
    'uses'  => 'HomeController@getPegawai'
]);


Route::group(['prefix' => 'cp', 'middleware' => 'auth'], function () {
	
	Route::get('dashboard', [
		'as' 	=> 	'cp.dashboard',
		'uses' 	=>	'PanelController@dashboard'
	]);

	Route::resource('pegawai', 'EmployeeController');

    Route::get('pegawai/{id}/file', [
        'as' => 'cp.pegawai.file',
        'uses' => 'EmployeeController@getFile'
        ]);

    Route::resource('instansi', 'InstituteController');

    Route::resource('jabatan', 'PositionController');

    Route::resource('callcenter', 'CallCenterController');

    Route::resource('users', 'UserController');

});

// Authentication Routes

Route::get('auth/login', 'Auth\AuthController@getLogin');

Route::post('auth/login', 'Auth\AuthController@postLogin');

Route::get('auth/logout', 'Auth\AuthController@getLogout');

resources/views/cp/instansi/create.blade.php
@extends('cp.master')

@section('content')

<div class="row">	
	<div class="col-md-6 col-md-offset-2">
		<h1 class="page-header">Menambah Data Instansi</h1>
		
		      <!-- Status Check -->
        @if (session('status'))
            <div class="alert alert-success">
              {{ session('status') }}
            </div>
        @endif
        <!-- Status Check -->
	
		{!! Form::open(['route' => 'cp.instansi.store', 'method' => 'post', 'files' => true]) !!}			

			<div class="form-group {{ ($errors->first('nama')) ? 'has-error' : '' }}">
				<label for="nama">Nama</label>
				{!! Form::text('nama', null, ['class' => 'form-control']) !!}
				{!! ($errors->first('nama')) ? $errors->first('nama', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('no_telp')) ? 'has-error' : '' }}">
				<label for="no_telp">No. Telepon</label>
				{!! Form::text('no_telp', null, ['class' => 'form-control']) !!}
				{!! ($errors->first('no_telp')) ? $errors->first('no_telp', '<span class="help-block">:message</span>') : ''!!}			
			</div>

			<div class="form-group {{ ($errors->first('alamat')) ? 'has-error' : '' }}">
				<label for="alamat">Alamat</label>
				{!! Form::textarea('alamat', null, ['rows' => 3, 'class' => 'form-control']) !!}
				{!! ($errors->first('alamat')) ? $errors->first('alamat', '<span class="help-block">:message</span>') : '' !!}
			</div>
			
			<hr>
			
			<div class="form-group">				
				<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Simpan</button>
			</div>
			
		{!! Form::close() !!}
	</div>
</div>

@endsection

resources/views/cp/instansi/edit.blade.php
@extends('cp.master')

@section('content')

<div class="row">	
	<div class="col-md-6 col-md-offset-2">
		<h1 class="page-header">Mengubah Data Instansi</h1>
		
		@if(Session::has('error'))
			<div class="alert alert-danger">
				{{ Session::get('error') }}
			</div>
		@endif

	    @if(session('success-update'))
	      	<div class="alert alert-success">
	           	{{ session('success-update') }}
	       	</div>
	    @elseif(session('error-update'))
	       	<div class="alert alert-danger">
	          	{{ session('error-update') }}
	       	</div>
	    @endif
	
		{!! Form::model($instansi, ['route' => ['cp.instansi.update', $instansi->id], 'method' => 'put', 'files' => true]) !!}

			<div class="form-group {{ ($errors->first('nama')) ? 'has-error' : '' }}">
				<label for="nama">Nama</label>
				{!! Form::text('nama', $instansi->name, ['class' => 'form-control']) !!}
				{!! ($errors->first('nama')) ? $errors->first('nama', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('no_telp')) ? 'has-error' : '' }}">
				<label for="no_telp">No. Telepon</label>
				{!! Form::text('no_telp', $instansi->phone_number, ['class' => 'form-control']) !!}
				{!! ($errors->first('no_telp')) ? $errors->first('no_telp', '<span class="help-block">:message</span>') : '' !!}
			</div>

			<div class="form-group {{ ($errors->first('alamat')) ? 'has-error' : '' }}">
				<label for="alamat">Alamat</label>
				{!! Form::textarea('alamat', $instansi->address, ['rows' => 3, 'class' => 'form-control']) !!}
				{!! ($errors->first('alamat')) ? $errors->first('alamat', '<span class="help-block">:message</span>') : '' !!}
			</div>
			
			<hr>
			
			<div class="form-group">				
				<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Simpan Perubahan</button>
			</div>
			
		{!! Form::close() !!}
	</div>
</div>

@endsection

resources/views/cp/instansi/index.blade.php
@extends('cp.master')

@section('content')
	
	<div class="row">
		<div class="col-md-12">
			<h1 class="page-header">Instansi <small>data master</small> <a href="{{ route('cp.instansi.create') }}" class="btn btn-primary pull-right">Tambah Data</a></h1>
			
	        @if (session('error-delete'))
	          <div class="alert alert-danger">
	            {{ session('error-delete') }}
	          </div>
	        @endif
	        @if (session('success-delete'))
	          <div class="alert alert-success">
	            {{ session('success-delete') }}
	          </div>
	        @endif

	        @if(session('success-create'))
	        	<div class="alert alert-success">
	            	{{ session('success-create') }}
	          	</div>
	        @elseif(session('error-create'))
	        	<div class="alert alert-danger">
	            	{{ session('error-create') }}
	          	</div>
	         @endif

			<table class="table table-condensed table-striped table-hover">
				<thead>
					<tr>
						<th>Nama Instansi</th>
						<th>Alamat</th>
						<th>Nomor Telepon</th>
						<th style="width: 100px">Aksi</th>
					</tr>
				</thead>
				<tbody>

					@foreach($instansi as $ins)
						
						<tr>
							<td>{{ $ins->name }}</td>
							<td>{{ $ins->address }}</td>
							<td>{{ $ins->phone_number }}</td>
							<td>
								<a href="{{ action('InstituteController@edit', ['id' => $ins->id]) }}" class="btn btn-warning btn-xs btn-block">Ubah</a>
								<a class="btn btn-danger btn-xs btn-block btn-delete" data-url="{{ action('InstituteController@destroy', $ins->id) }}" data-title="{{ $ins->name }}">Hapus</a>																
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
			{!! $instansi->render() !!}
		</div>
	</div>
@endsection